FEAT : added mockbee and rendering products
zoyatanweer/falcon-store-react pull request #8
Opened 2022-03-28 15:35 UTC by zoyatanweer

- added mockbee to the project
- rendered products from backend

Files to check:
- components/products/Products.jsx
- Context/data/Data-Context.jsx

2022-03-28 15:52 UTC, dev-prabhat requested changes
some changes required but code is file and clean

2022-03-28 15:52 UTC, dev-prabhat commented on .eslintcache
> +[{"C:\\Users\\hp\\Documents\\VScode\\neog'22\\falcon-store-react\\falcon-store-react\\src\\index.js":"1","C:\\Users\\hp\\Documents\\VScode\\neog'22\\falcon-store-react\\falcon-store-react\\src\\serve
I think this file can be removed

2022-03-28 15:52 UTC, dev-prabhat commented on src/components/products/Products.jsx
> +// import { Products } from "../../data/data";
removed this commented code

2022-03-28 15:52 UTC, dev-prabhat commented on src/Context/data/Data-Context.jsx
> +      setData((previous) => (previous = responseData));
if this line works fine you can merge

2022-03-28 15:55 UTC, developer-anand approved these changes
Nice Clean Code, good to go with changes.

2022-03-28 17:02 UTC, tonymike99 approved these changes
Hi Zoya :)
Everything looks good. 

Suggestion: add the .eslintcache to .gitignore

2022-03-29 16:51 UTC, zoyatanweer commented
Thankyou guys for your reviews.

2022-03-30 13:42 UTC, merged